### PR TITLE
Add Mavlink common and minimal headers and xml files

### PR DESCRIPTION
**Pull request by filipembedded**
Added pregenerated headers in gen directory inside src/protocol/mavlink/ ,with following xml files for common and minimal

### CODE REVIEW

**Review by mileticveljko — COMMENTED** [review]
This pre-generated MAVLink headers are needed for initial development of Sitl!

**Comment by DNedic** [comment]
I am of the opinion that we shouldnt generate anything inside the project source dir and that every build artefact (which generated sources are) should go to `build`. 

Additionally, the generation should be a part of the build process, and not require manual intervention, as this could cause a discrepancy between the source (message sources) and the build result, causing possible confusion and missed bugs when commiting changes. (this especially comes into play with the CI builds)

Please take a look at how this is done in the [ULOG support branch](https://github.com/eurus-project/efc/tree/feat/add_ulog_support).

Finally, a small nitpick, `src/messages/` is to me a bit nicer than `src/protocol`, but this is a personal taste thing.

**Comment by mileticveljko** [comment]
The idea is for pre-generated headers to be removed when that generation is moved into build process. This generated code will indeed be generated into something like `build` directory that is ignored by git.

**Comment by mileticveljko** [comment]
This pre-generated mavlink headers in the source code was originally my idea - this will be done another way.

**Pull request closed without merging**
